import { g as ChannelMessageActionContext } from "../types.core-CInSoozE.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { Ci as PluginRuntime, b as OpenClawPluginApi, fo as emptyPluginConfigSchema } from "../host-capability-types-BQXGgYpD.js";
import { t as ChannelPlugin } from "../types.plugin-dRT3k41V.js";
import { i as buildChannelConfigSchema } from "../config-schema-55t5MIyq.js";
import { o as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-CCWGet6c.js";
import { n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields } from "../config-helpers-DnkmwS2K.js";
import { n as formatPairingApproveHint } from "../helpers-BBnGZWZu.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFjlYpMw.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-DIumAwoK.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };