import { _ as resolveGatewayPort } from "../../paths-CqeDjSA4.js";
import { n as resolvePreferredOpenClawTmpDir } from "../../tmp-openclaw-dir-BBjU-hqW.js";
import { n as renderQrPngDataUrl, r as writeQrPngTempFile, t as renderQrPngBase64 } from "../../qr-image-BU2pvgPz.js";
import { t as runPluginCommandWithTimeout } from "../../run-command-CMMxnUxU.js";
import { t as definePluginEntry } from "../../plugin-entry-B4wzLSpS.js";
import { r as resolveTailscaleServeGatewayUrlsWithRunner, t as resolveTailnetHostWithRunner } from "../../tailscale-status-C8p6ZWI6.js";
import { t as resolveGatewayBindUrl } from "../../gateway-bind-url-CO8cGU-C.js";
import { f as revokeDeviceBootstrapToken, j as PAIRING_SETUP_BOOTSTRAP_PROFILE, o as issueDeviceBootstrapToken, t as clearDeviceBootstrapTokens } from "../../device-bootstrap-ftwhmc0m.js";
import { d as listDevicePairing, r as approveDevicePairing } from "../../device-pairing-CkbDK__R.js";
import { t as resolveAdvertisedLanHost } from "../../gateway-runtime-Vk_KkezP.js";
import "../../api-BmoSz0hL.js";
export { PAIRING_SETUP_BOOTSTRAP_PROFILE, approveDevicePairing, clearDeviceBootstrapTokens, definePluginEntry, issueDeviceBootstrapToken, listDevicePairing, renderQrPngBase64, renderQrPngDataUrl, resolveAdvertisedLanHost, resolveGatewayBindUrl, resolveGatewayPort, resolvePreferredOpenClawTmpDir, resolveTailnetHostWithRunner, resolveTailscaleServeGatewayUrlsWithRunner, revokeDeviceBootstrapToken, runPluginCommandWithTimeout, writeQrPngTempFile };
