import { f as redactSensitiveText, j as compileSafeRegexDetailed } from "../redact-CWP17HFN.js";
import { t as FsSafeError } from "../errors-CQDiIdj7.js";
import { a as isPathInside } from "../path-D138yf8v.js";
import { a as resolveAbsolutePathForRead, c as pathExistsSync, i as findExistingAncestor, n as canonicalPathFromExistingAncestor, o as resolveAbsolutePathForWrite, s as pathExists } from "../absolute-path-CYFPfAjt.js";
import { d as resolveExistingPathsWithinRoot, f as resolveStrictExistingPathsWithinRoot, h as sanitizeUntrustedFileName, i as writeExternalFileWithinRoot, m as resolveLocalPathFromRootsSync, r as root, u as pathScope } from "../fs-safe-CmrQUApq.js";
import { n as openLocalFileSafely } from "../root-impl-BbMR4leC.js";
import { c as assertNoSymlinkParents, i as readRegularFileSync, l as assertNoSymlinkParentsSync, o as statRegularFile, r as readRegularFile, s as statRegularFileSync, t as appendRegularFile } from "../regular-file-Dwz6p59y.js";
import { r as withTimeout } from "../timing-8WD1In27.js";
import { n as extractErrorCode, r as formatErrorMessage } from "../errors-Ccx0R-_Z.js";
import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-DnyL0lW9.js";
import { t as movePathWithCopyFallback } from "../move-path-DwtBa1y6.js";
import { t as replaceFileAtomic } from "../replace-file-CLSCJ1qR.js";
import { t as normalizeHostname } from "../hostname-_16721Le.js";
import { i as hasProxyEnvConfigured } from "../proxy-env-TVpcGZHW.js";
import { _ as resolvePinnedHostnameWithPolicy, d as isPrivateNetworkAllowedByPolicy, p as matchesHostnameAllowlist, t as SsrFBlockedError } from "../ssrf-arYIaOWE.js";
import { n as privateFileStoreSync } from "../private-file-store-CcE8O0xd.js";
import { t as safeEqualSecret } from "../secret-equal-DRsL8lKD.js";
import { r as ensurePortAvailable } from "../ports-8zXv4rN7.js";
import { a as wrapExternalContent, i as truncateSanitizedExternalContent, o as wrapWebContent } from "../external-content-IQUFD6xt.js";
import { a as parseAccessGroupAllowFromEntry } from "../allow-from-D4kg2zcb.js";
import { o as resolvePinnedMainDmOwnerFromAllowlist } from "../dm-policy-shared-5Uqxw7WI.js";
import { n as filterSupplementalContextItems, r as shouldIncludeSupplementalContext, t as evaluateSupplementalContextVisibility } from "../context-visibility-C5CaKMWO.js";
import { t as expandAllowFromWithAccessGroups } from "../access-groups-DdAoO5yT.js";
import { n as buildChannelMetadata, r as buildUntrustedChannelMetadata, t as fileExists } from "../security-runtime-qrFVi6LG.js";
export { FsSafeError, SsrFBlockedError, appendRegularFile, assertNoSymlinkParents, assertNoSymlinkParentsSync, buildChannelMetadata, buildUntrustedChannelMetadata, canonicalPathFromExistingAncestor, compileSafeRegexDetailed, ensurePortAvailable, evaluateSupplementalContextVisibility, expandAllowFromWithAccessGroups, extractErrorCode, fileExists, filterSupplementalContextItems, findExistingAncestor, formatErrorMessage, hasProxyEnvConfigured, isPathInside, isPrivateNetworkAllowedByPolicy, matchesHostnameAllowlist, movePathWithCopyFallback, normalizeHostname, openLocalFileSafely, parseAccessGroupAllowFromEntry, pathExists, pathExistsSync, pathScope, privateFileStoreSync, readRegularFile, readRegularFileSync, redactSensitiveText, replaceFileAtomic, resolveAbsolutePathForRead, resolveAbsolutePathForWrite, resolveExistingPathsWithinRoot, resolveLocalPathFromRootsSync, resolvePinnedHostnameWithPolicy, resolvePinnedMainDmOwnerFromAllowlist, resolvePreferredOpenClawTmpDir, resolveStrictExistingPathsWithinRoot, root, safeEqualSecret, sanitizeUntrustedFileName, shouldIncludeSupplementalContext, statRegularFile, statRegularFileSync, truncateSanitizedExternalContent, withTimeout, wrapExternalContent, wrapWebContent, writeExternalFileWithinRoot };
