import { Jn as createChannelPluginBase, Kn as buildChannelOutboundSessionRoute, Un as ChannelOutboundSessionRouteParams, Xn as defineChannelPluginEntry, Xo as OpenClawPluginApi, Yn as createChatChannelPlugin, Zn as defineSetupPluginEntry, er as recoverCurrentThreadSessionId, nc as PluginCommandContext, nr as stripTargetKindPrefix, qn as buildThreadAwareOutboundSessionRoute, tr as stripChannelTargetPrefix, yr as PluginRuntime } from "../agent-harness-runtime-CESurA0d.js";
import { r as OpenClawConfig } from "../types.openclaw-CflOMr0r.js";
import { r as ChannelConfigUiHint } from "../types.config-CGDAHrEQ.js";
import { t as ChannelPlugin } from "../types.plugin-B_jWpFWB.js";
import { r as tryReadSecretFileSync } from "../secret-file-CP3QFrME.js";
import { i as buildChannelConfigSchema } from "../config-schema-BccvCAt7.js";
import { t as clearAccountEntryFields } from "../config-helpers-BuHGjaZg.js";
import { r as parseOptionalDelimitedEntries } from "../helpers-DGOlajlw.js";
import { t as createChannelConfigUiHints } from "../channel-core-CNMH5Zbo.js";
export { type ChannelConfigUiHint, type ChannelOutboundSessionRouteParams, type ChannelPlugin, type OpenClawConfig, type OpenClawPluginApi, type PluginCommandContext, type PluginRuntime, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildThreadAwareOutboundSessionRoute, clearAccountEntryFields, createChannelConfigUiHints, createChannelPluginBase, createChatChannelPlugin, defineChannelPluginEntry, defineSetupPluginEntry, parseOptionalDelimitedEntries, recoverCurrentThreadSessionId, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };