import { Xo as OpenClawPluginApi, jl as emptyPluginConfigSchema, yr as PluginRuntime } from "../agent-harness-runtime-CESurA0d.js";
import { g as ChannelMessageActionContext } from "../types.core-CMY5bxhQ.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { t as ChannelPlugin } from "../types.plugin-B_jWpFWB.js";
import { i as buildChannelConfigSchema } from "../config-schema-BccvCAt7.js";
import { o as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-BqTgpSq9.js";
import { i as setAccountEnabledInConfigSection, r as deleteAccountFromConfigSection, t as clearAccountEntryFields } from "../config-helpers-BuHGjaZg.js";
import { n as formatPairingApproveHint } from "../helpers-DGOlajlw.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFs8lRw3.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-BYdcEUQx.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };