import { c as redactSensitiveText, k as compileSafeRegexDetailed } from "../redact-Cl7lwBnl.js";
import { t as FsSafeError } from "../errors-CQDiIdj7.js";
import { a as isPathInside } from "../path-D138yf8v.js";
import { a as resolveAbsolutePathForRead, c as pathExistsSync, i as findExistingAncestor, n as canonicalPathFromExistingAncestor, o as resolveAbsolutePathForWrite, s as pathExists } from "../absolute-path-BseY-yOe.js";
import { d as resolveExistingPathsWithinRoot, f as resolveStrictExistingPathsWithinRoot, h as sanitizeUntrustedFileName, i as writeExternalFileWithinRoot, m as resolveLocalPathFromRootsSync, r as root, u as pathScope } from "../fs-safe-C9N8pCh1.js";
import { n as openLocalFileSafely } from "../root-impl-YIsYOvqy.js";
import { c as assertNoSymlinkParents, i as readRegularFileSync, l as assertNoSymlinkParentsSync, o as statRegularFile, r as readRegularFile, s as statRegularFileSync, t as appendRegularFile } from "../regular-file-CXw3t-8J.js";
import { r as withTimeout } from "../timing-8WD1In27.js";
import { n as extractErrorCode, r as formatErrorMessage } from "../errors-CSNUPl5U.js";
import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-BBjU-hqW.js";
import { t as movePathWithCopyFallback } from "../move-path-Du9NWvvx.js";
import { t as replaceFileAtomic } from "../replace-file-sXUFaaUi.js";
import { t as normalizeHostname } from "../hostname-_16721Le.js";
import { i as hasProxyEnvConfigured } from "../proxy-env-CVpLKmqL.js";
import { _ as resolvePinnedHostnameWithPolicy, d as isPrivateNetworkAllowedByPolicy, p as matchesHostnameAllowlist, t as SsrFBlockedError } from "../ssrf-UFPP-fbI.js";
import { n as privateFileStoreSync } from "../private-file-store-p6c2I0-s.js";
import { t as safeEqualSecret } from "../secret-equal-DRsL8lKD.js";
import { r as ensurePortAvailable } from "../ports-DGhqGvd9.js";
import { a as wrapExternalContent, i as truncateSanitizedExternalContent, o as wrapWebContent } from "../external-content-IQUFD6xt.js";
import { a as parseAccessGroupAllowFromEntry } from "../allow-from-D4kg2zcb.js";
import { o as resolvePinnedMainDmOwnerFromAllowlist } from "../dm-policy-shared-DqJhfdto.js";
import { n as buildChannelMetadata, r as buildUntrustedChannelMetadata, t as fileExists } from "../security-runtime-Bm9RUgAZ.js";
import { n as filterSupplementalContextItems, r as shouldIncludeSupplementalContext, t as evaluateSupplementalContextVisibility } from "../context-visibility-C5CaKMWO.js";
import { t as expandAllowFromWithAccessGroups } from "../access-groups-DdAoO5yT.js";
export { FsSafeError, SsrFBlockedError, appendRegularFile, assertNoSymlinkParents, assertNoSymlinkParentsSync, buildChannelMetadata, buildUntrustedChannelMetadata, canonicalPathFromExistingAncestor, compileSafeRegexDetailed, ensurePortAvailable, evaluateSupplementalContextVisibility, expandAllowFromWithAccessGroups, extractErrorCode, fileExists, filterSupplementalContextItems, findExistingAncestor, formatErrorMessage, hasProxyEnvConfigured, isPathInside, isPrivateNetworkAllowedByPolicy, matchesHostnameAllowlist, movePathWithCopyFallback, normalizeHostname, openLocalFileSafely, parseAccessGroupAllowFromEntry, pathExists, pathExistsSync, pathScope, privateFileStoreSync, readRegularFile, readRegularFileSync, redactSensitiveText, replaceFileAtomic, resolveAbsolutePathForRead, resolveAbsolutePathForWrite, resolveExistingPathsWithinRoot, resolveLocalPathFromRootsSync, resolvePinnedHostnameWithPolicy, resolvePinnedMainDmOwnerFromAllowlist, resolvePreferredOpenClawTmpDir, resolveStrictExistingPathsWithinRoot, root, safeEqualSecret, sanitizeUntrustedFileName, shouldIncludeSupplementalContext, statRegularFile, statRegularFileSync, truncateSanitizedExternalContent, withTimeout, wrapExternalContent, wrapWebContent, writeExternalFileWithinRoot };
