import { Xo as OpenClawPluginApi, jl as emptyPluginConfigSchema, yr as PluginRuntime } from "../agent-harness-runtime-D3DJE4wK.js";
import { g as ChannelMessageActionContext } from "../types.core-CECrTHHY.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { t as ChannelPlugin } from "../types.plugin-CEsbXbnm.js";
import { i as buildChannelConfigSchema } from "../config-schema-Bul-U1Mi.js";
import { o as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-5LHH8Cll.js";
import { i as setAccountEnabledInConfigSection, r as deleteAccountFromConfigSection, t as clearAccountEntryFields } from "../config-helpers-CldXV1LK.js";
import { n as formatPairingApproveHint } from "../helpers-Df_pG4P-.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFs8lRw3.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-DCJB73uh.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };