import { Jn as createChannelPluginBase, Kn as buildChannelOutboundSessionRoute, Un as ChannelOutboundSessionRouteParams, Xn as defineChannelPluginEntry, Xo as OpenClawPluginApi, Yn as createChatChannelPlugin, Zn as defineSetupPluginEntry, er as recoverCurrentThreadSessionId, nc as PluginCommandContext, nr as stripTargetKindPrefix, qn as buildThreadAwareOutboundSessionRoute, tr as stripChannelTargetPrefix, yr as PluginRuntime } from "../agent-harness-runtime-D3DJE4wK.js";
import { r as OpenClawConfig } from "../types.openclaw-Cjm06lg9.js";
import { r as ChannelConfigUiHint } from "../types.config-CGDAHrEQ.js";
import { t as ChannelPlugin } from "../types.plugin-CEsbXbnm.js";
import { r as tryReadSecretFileSync } from "../secret-file-CP3QFrME.js";
import { i as buildChannelConfigSchema } from "../config-schema-Bul-U1Mi.js";
import { t as clearAccountEntryFields } from "../config-helpers-CldXV1LK.js";
import { r as parseOptionalDelimitedEntries } from "../helpers-Df_pG4P-.js";
import { t as createChannelConfigUiHints } from "../channel-core-Dl_bFrnt.js";
export { type ChannelConfigUiHint, type ChannelOutboundSessionRouteParams, type ChannelPlugin, type OpenClawConfig, type OpenClawPluginApi, type PluginCommandContext, type PluginRuntime, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildThreadAwareOutboundSessionRoute, clearAccountEntryFields, createChannelConfigUiHints, createChannelPluginBase, createChatChannelPlugin, defineChannelPluginEntry, defineSetupPluginEntry, parseOptionalDelimitedEntries, recoverCurrentThreadSessionId, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };