import { n as AcpRuntimeError } from "../../errors-CIvv7cvF.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-BRqK6RmF.js";
import { a as buildChannelConfigSchema } from "../../config-schema-C8KVhsqS.js";
import { o as getChatChannelMeta } from "../../registry-BAJij-wJ.js";
import { _ as readToolStringParam, f as readNumberParam, g as readStringOrNumberParam, h as readStringArrayParam, m as readReactionParams } from "../../common-ciEJghJz.js";
import { t as jsonResult } from "../../tool-results-BCM3fdVS.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-6BJZGtr6.js";
import { r as resolvePollMaxSelections } from "../../polls-C-v11_tu.js";
import { t as clearAccountEntryFields } from "../../config-helpers-CzQqpZhA.js";
import { n as formatPairingApproveHint } from "../../helpers-C-WC19Mc.js";
import { c as resolveConfiguredFromCredentialStatuses, i as projectCredentialSnapshotFields } from "../../account-snapshot-fields-BE7s6a11.js";
import { r as makeProxyFetch } from "../../proxy-fetch-CxekH4gx.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-DrlSGPoD.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-DQlQpdHk.js";
import { t as resolveTelegramToken } from "../../token-C1f3v7zW.js";
import "../../acp-runtime-BmPKVD_7.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DNhqI-OE.js";
import "../../channel-plugin-common-o8GmRUQb.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-CRFbyFxI.js";
import "../../channel-status-BgzZxd8A.js";
import "../../channel-config-schema-Heqt9qxQ.js";
import "../../channel-actions-Ht8PCq9o.js";
import "../../channel-core-eALo86Vk.js";
import { r as setTelegramRuntime } from "../../runtime-D4cq5Nic.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-D_TTDJeT.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-B6kdtLDb.js";
import "../../command-config-DNZ3c87b.js";
import { n as TelegramConfigSchema } from "../../config-schema-DZjpsK1e.js";
import { a as setTelegramThreadBindingMaxAgeBySessionKey, i as setTelegramThreadBindingIdleTimeoutBySessionKey, n as getTelegramThreadBindingManager, r as resetTelegramThreadBindingsForTests, t as createTelegramThreadBindingManager } from "../../thread-bindings-BuyfUBV8.js";
import { E as editMessageTelegram, Ft as resolveTelegramRuntimeGroupPolicy, G as editForumTopicTelegram, J as pinMessageTelegram, K as renameForumTopicTelegram, T as editMessageReplyMarkupTelegram, W as createForumTopicTelegram, X as sendTypingTelegram, Y as reactMessageTelegram, Z as unpinMessageTelegram, m as sendMessageTelegram, n as sendStickerTelegram, q as deleteMessageTelegram, t as sendPollTelegram } from "../../send-E-0j6XqP.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-Ds4ydsWS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readToolStringParam as readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
