import { i as normalizeXaiModelId } from "../../model-id-DjgicLW1.js";
import { HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING, XAI_TOOL_SCHEMA_PROFILE, applyXaiModelCompat } from "./model-compat.js";
import { buildXaiProvider } from "./provider-catalog.js";
import { XAI_DEFAULT_MODEL_REF, applyXaiConfig, applyXaiProviderConfig } from "./onboard.js";
import { buildXaiImageGenerationProvider } from "./image-generation-provider.js";
import { XAI_BASE_URL, XAI_DEFAULT_CONTEXT_WINDOW, XAI_DEFAULT_IMAGE_MODEL, XAI_DEFAULT_MAX_TOKENS, XAI_DEFAULT_MODEL_ID, XAI_IMAGE_MODELS, buildXaiCatalogModels, buildXaiModelDefinition, resolveXaiCatalogEntry } from "./model-definitions.js";
import { isModernXaiModel, resolveXaiForwardCompatModel } from "./provider-models.js";
import { applyXaiRuntimeModelCompat } from "./runtime-model-compat.js";
import { resolveXaiTransport } from "./provider-routing.js";
export { HTML_ENTITY_TOOL_CALL_ARGUMENTS_ENCODING, XAI_BASE_URL, XAI_DEFAULT_CONTEXT_WINDOW, XAI_DEFAULT_IMAGE_MODEL, XAI_DEFAULT_MAX_TOKENS, XAI_DEFAULT_MODEL_ID, XAI_DEFAULT_MODEL_REF, XAI_IMAGE_MODELS, XAI_TOOL_SCHEMA_PROFILE, applyXaiConfig, applyXaiModelCompat, applyXaiProviderConfig, applyXaiRuntimeModelCompat, buildXaiCatalogModels, buildXaiImageGenerationProvider, buildXaiModelDefinition, buildXaiProvider, isModernXaiModel, normalizeXaiModelId, resolveXaiCatalogEntry, resolveXaiForwardCompatModel, resolveXaiTransport };