import { _ as resolveGatewayPort } from "../../paths-CqeDjSA4.js";
import { n as resolvePreferredOpenClawTmpDir } from "../../tmp-openclaw-dir-BBjU-hqW.js";
import { n as renderQrPngDataUrl, r as writeQrPngTempFile, t as renderQrPngBase64 } from "../../qr-image-Lc6TCYaQ.js";
import { t as runPluginCommandWithTimeout } from "../../run-command-CDTGk_EJ.js";
import { t as definePluginEntry } from "../../plugin-entry-Ckewxva0.js";
import { r as resolveTailscaleServeGatewayUrlsWithRunner, t as resolveTailnetHostWithRunner } from "../../tailscale-status-Dgns1405.js";
import { t as resolveGatewayBindUrl } from "../../gateway-bind-url-CO8cGU-C.js";
import { f as revokeDeviceBootstrapToken, j as PAIRING_SETUP_BOOTSTRAP_PROFILE, o as issueDeviceBootstrapToken, t as clearDeviceBootstrapTokens } from "../../device-bootstrap-B0GG6gmu.js";
import { d as listDevicePairing, r as approveDevicePairing } from "../../device-pairing-CobL1ZXN.js";
import { t as resolveAdvertisedLanHost } from "../../gateway-runtime-Bdl1Q2-8.js";
import "../../api-DEuIVPlk.js";
export { PAIRING_SETUP_BOOTSTRAP_PROFILE, approveDevicePairing, clearDeviceBootstrapTokens, definePluginEntry, issueDeviceBootstrapToken, listDevicePairing, renderQrPngBase64, renderQrPngDataUrl, resolveAdvertisedLanHost, resolveGatewayBindUrl, resolveGatewayPort, resolvePreferredOpenClawTmpDir, resolveTailnetHostWithRunner, resolveTailscaleServeGatewayUrlsWithRunner, revokeDeviceBootstrapToken, runPluginCommandWithTimeout, writeQrPngTempFile };
