import { P as ChannelApprovalNativeTarget } from "../approval-handler-runtime-types-BZ-ScdGo.js";
import { a as resolveApprovalRequestSessionTarget, i as resolveApprovalRequestSessionConversation, n as ExecApprovalSessionTarget, o as resolveExecApprovalSessionTarget, r as resolveApprovalRequestOriginTarget, t as ApprovalRequestSessionConversation } from "../exec-approval-session-target-C-1nxETh.js";
import { a as createChannelApprovalForwardingEvaluator, c as createNativeApprovalChannelRouteGates, d as nativeApprovalTargetsMatch, f as resolveApprovalKind, l as createNativeApprovalForwardingFallbackSuppressor, n as ChannelApprovalForwardingEligibilityParams, o as createChannelApproverDmTargetResolver, p as shouldSuppressLocalNativeExecApprovalPrompt, r as ChannelApprovalPotentialRouteParams, s as createChannelNativeOriginTargetResolver, t as ChannelApprovalExplicitTargetEligibilityParams, u as createNativeApprovalMessagingTargetResolvers } from "../approval-native-helpers-BoJDIuV0.js";
import { i as resolveApprovalRequestChannelAccountId, n as doesApprovalRequestSelectChannelAccount, r as resolveApprovalRequestAccountId, t as doesApprovalRequestMatchChannelAccount } from "../approval-request-account-binding-BTZ6R5VQ.js";

//#region src/infra/approval-native-target-key.d.ts
/** Builds the stable dedupe key used to compare channel-native approval targets. */
declare function buildChannelApprovalNativeTargetKey(target: ChannelApprovalNativeTarget): string;
//#endregion
export { type ApprovalRequestSessionConversation, type ChannelApprovalExplicitTargetEligibilityParams, type ChannelApprovalForwardingEligibilityParams, type ChannelApprovalPotentialRouteParams, type ExecApprovalSessionTarget, buildChannelApprovalNativeTargetKey, createChannelApprovalForwardingEvaluator, createChannelApproverDmTargetResolver, createChannelNativeOriginTargetResolver, createNativeApprovalChannelRouteGates, createNativeApprovalForwardingFallbackSuppressor, createNativeApprovalMessagingTargetResolvers, doesApprovalRequestMatchChannelAccount, doesApprovalRequestSelectChannelAccount, nativeApprovalTargetsMatch, resolveApprovalKind, resolveApprovalRequestAccountId, resolveApprovalRequestChannelAccountId, resolveApprovalRequestOriginTarget, resolveApprovalRequestSessionConversation, resolveApprovalRequestSessionTarget, resolveExecApprovalSessionTarget, shouldSuppressLocalNativeExecApprovalPrompt };