import { g as ChannelMessageActionContext } from "../types.core-D43joVXt.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { Ci as PluginRuntime, b as OpenClawPluginApi, fo as emptyPluginConfigSchema } from "../host-capability-types-3XBDy-df.js";
import { t as ChannelPlugin } from "../types.plugin-C7vGTyQq.js";
import { i as buildChannelConfigSchema } from "../config-schema-55t5MIyq.js";
import { o as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-CKp-7E-H.js";
import { n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields } from "../config-helpers-C8_ALY3e.js";
import { n as formatPairingApproveHint } from "../helpers-CMb1g7xG.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFjlYpMw.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-D0yTx4R-.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };