import { r as OpenClawConfig } from "../types.openclaw-a_kGc1gJ.js";
import { r as ChannelConfigUiHint } from "../types.config-C6_VK-8V.js";
import { Ci as PluginRuntime, U as PluginCommandContext, b as OpenClawPluginApi } from "../host-capability-types-3XBDy-df.js";
import { t as ChannelPlugin } from "../types.plugin-C7vGTyQq.js";
import { r as tryReadSecretFileSync } from "../secret-file-DTtIdHTB.js";
import { a as buildThreadAwareOutboundSessionRoute, c as defineChannelPluginEntry, f as recoverCurrentThreadSessionId, i as buildChannelOutboundSessionRoute, l as defineSetupPluginEntry, m as stripTargetKindPrefix, o as createChannelPluginBase, p as stripChannelTargetPrefix, s as createChatChannelPlugin, t as ChannelOutboundSessionRouteParams } from "../core-fOv5e3vZ.js";
import { i as buildChannelConfigSchema } from "../config-schema-55t5MIyq.js";
import { t as clearAccountEntryFields } from "../config-helpers-C8_ALY3e.js";
import { r as parseOptionalDelimitedEntries } from "../helpers-CMb1g7xG.js";
import { t as createChannelConfigUiHints } from "../channel-core-CZMDz4MW.js";
export { type ChannelConfigUiHint, type ChannelOutboundSessionRouteParams, type ChannelPlugin, type OpenClawConfig, type OpenClawPluginApi, type PluginCommandContext, type PluginRuntime, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildThreadAwareOutboundSessionRoute, clearAccountEntryFields, createChannelConfigUiHints, createChannelPluginBase, createChatChannelPlugin, defineChannelPluginEntry, defineSetupPluginEntry, parseOptionalDelimitedEntries, recoverCurrentThreadSessionId, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };