import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-BH0zJUew.js";
import { a as buildChannelConfigSchema } from "../../config-schema-ikPYPY3Q.js";
import { o as getChatChannelMeta } from "../../registry-DbgR8dhg.js";
import { _ as readToolStringParam, f as readNumberParam, g as readStringOrNumberParam, h as readStringArrayParam, m as readReactionParams } from "../../common-CI1GnPjt.js";
import { t as jsonResult } from "../../tool-results-BCM3fdVS.js";
import { n as AcpRuntimeError } from "../../errors-MW5Rkd8s.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DSzK-IPe.js";
import { r as resolvePollMaxSelections } from "../../polls-C-v11_tu.js";
import { t as clearAccountEntryFields } from "../../config-helpers-Dwx1uD2b.js";
import { n as formatPairingApproveHint } from "../../helpers-cxjR1aAq.js";
import { c as resolveConfiguredFromCredentialStatuses, i as projectCredentialSnapshotFields } from "../../account-snapshot-fields-DPncjgDN.js";
import { r as makeProxyFetch } from "../../proxy-fetch-CIh_-v0I.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-CSNgL9pY.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-CWN0faxV.js";
import { t as resolveTelegramToken } from "../../token--XtttkKB.js";
import "../../acp-runtime-Dkil17tj.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DNhqI-OE.js";
import "../../channel-plugin-common-DgLrUXRP.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-CopMHs_f.js";
import "../../channel-status-Bt34VDhN.js";
import "../../channel-config-schema-DeVmAx-r.js";
import "../../channel-actions-D2ZN81sL.js";
import "../../channel-core-DYDgmix_.js";
import { n as parseTelegramTopicConversation } from "../../topic-conversation-Cl4csGES.js";
import { r as setTelegramRuntime } from "../../runtime-D4cq5Nic.js";
import { a as shouldSuppressTelegramExecApprovalForwardingFallback, i as buildTelegramExecApprovalPendingPayload, n as monitorTelegramProvider, o as telegramMessageActions, t as probeTelegram } from "../../probe-D_qkZ9qA.js";
import "../../command-config-BRHFowmK.js";
import { n as TelegramConfigSchema } from "../../config-schema-B4PrDKNq.js";
import { i as setTelegramThreadBindingMaxAgeBySessionKey, n as getTelegramThreadBindingManager, r as setTelegramThreadBindingIdleTimeoutBySessionKey, t as createTelegramThreadBindingManager } from "../../thread-bindings-DGw43h4R.js";
import { A as unpinMessageTelegram, C as editForumTopicTelegram, D as pinMessageTelegram, O as reactMessageTelegram, S as createForumTopicTelegram, T as deleteMessageTelegram, b as editMessageTelegram, gt as resolveTelegramRuntimeGroupPolicy, k as sendTypingTelegram, n as sendStickerTelegram, t as sendPollTelegram, u as sendMessageTelegram, w as renameForumTopicTelegram, y as editMessageReplyMarkupTelegram } from "../../send-B3vmt1UE.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-Ds4ydsWS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readToolStringParam as readStringParam, renameForumTopicTelegram, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
