/**
 * Public SDK subpath for memory host storage, indexing, and search primitives.
 */
export {
  buildFileEntry,
  buildMemoryReadResult,
  buildMemoryReadResultFromSlice,
  buildMultimodalChunkForIndexing,
  chunkMarkdown,
  closeMemorySqliteWalMaintenance,
  configureMemorySqliteWalMaintenance,
  cosineSimilarity,
  DEFAULT_MEMORY_READ_LINES,
  DEFAULT_MEMORY_READ_MAX_CHARS,
  buildMemoryLifecycleWhereClause,
  buildMemoryScopeFilterClause,
  deriveMemoryScope,
  ensureDir,
  ensureMemoryIndexSchema,
  ensureMemoryMetadataColumns,
  hashText,
  isFileMissingError,
  isTransientMemoryReadError,
  listMemoryFiles,
  loadSqliteVecExtension,
  MEMORY_EMBEDDING_CACHE_TABLE,
  MEMORY_INDEX_CHUNKS_TABLE,
  MEMORY_INDEX_FTS_TABLE,
  MEMORY_INDEX_META_TABLE,
  MEMORY_INDEX_SOURCES_TABLE,
  MEMORY_INDEX_STATE_TABLE,
  MEMORY_INDEX_VECTOR_TABLE,
  normalizeExtraMemoryPaths,
  normalizeMemoryFeedbackKind,
  normalizeMemoryLifecycle,
  normalizeMemoryScope,
  normalizeMemoryScopes,
  parseEmbedding,
  readMemoryFile,
  retryTransientMemoryRead,
  remapChunkLines,
  requireNodeSqlite,
  resolveMemoryBackendConfig,
  runWithConcurrency,
  statRegularFile,
} from "../../packages/memory-host-sdk/src/engine-storage.js";

export type {
  MemoryDoctorReport,
  MemoryEmbeddingProbeResult,
  MemoryFeedbackKind,
  MemoryFeedbackResult,
  MemoryChunk,
  MemoryFileEntry,
  MemoryLifecycle,
  MemoryProviderStatus,
  MemoryReadResult,
  MemorySearchManager,
  MemorySearchResult,
  MemorySearchRuntimeDebug,
  MemorySearchTrace,
  MemoryScope,
  MemorySource,
  MemorySyncProgressUpdate,
  ResolvedMemoryBackendConfig,
  ResolvedQmdConfig,
  ResolvedQmdMcporterConfig,
} from "../../packages/memory-host-sdk/src/engine-storage.js";
