import { c as redactSensitiveText, k as compileSafeRegexDetailed } from "../redact-DP7p9QfH.js";
import { t as FsSafeError } from "../errors-hdcLXK2n.js";
import { a as isPathInside } from "../path-CYL8StfC.js";
import { a as resolveAbsolutePathForRead, c as pathExistsSync, i as findExistingAncestor, n as canonicalPathFromExistingAncestor, o as resolveAbsolutePathForWrite, s as pathExists } from "../absolute-path-DBVN5h2m.js";
import { d as resolveExistingPathsWithinRoot, f as resolveStrictExistingPathsWithinRoot, h as sanitizeUntrustedFileName, i as writeExternalFileWithinRoot, m as resolveLocalPathFromRootsSync, r as root, u as pathScope } from "../fs-safe-X_oyl7Rx.js";
import { n as openLocalFileSafely } from "../root-impl-DNOINk8h.js";
import { c as assertNoSymlinkParents, i as readRegularFileSync, l as assertNoSymlinkParentsSync, o as statRegularFile, r as readRegularFile, s as statRegularFileSync, t as appendRegularFile } from "../regular-file-SotPWt-b.js";
import { r as withTimeout } from "../timing-DpgMro2Q.js";
import { n as extractErrorCode, r as formatErrorMessage } from "../errors-CqPTYU6G.js";
import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-BBjU-hqW.js";
import { t as movePathWithCopyFallback } from "../move-path-aeI1MbfK.js";
import { t as replaceFileAtomic } from "../replace-file-Bcj2RH0f.js";
import { t as normalizeHostname } from "../hostname-_16721Le.js";
import { i as hasProxyEnvConfigured } from "../proxy-env-CVpLKmqL.js";
import { _ as resolvePinnedHostnameWithPolicy, d as isPrivateNetworkAllowedByPolicy, p as matchesHostnameAllowlist, t as SsrFBlockedError } from "../ssrf-CQ4RdJXm.js";
import { n as privateFileStoreSync } from "../private-file-store-CQOUjKsU.js";
import { t as safeEqualSecret } from "../secret-equal-DRsL8lKD.js";
import { r as ensurePortAvailable } from "../ports-pcwgnLvC.js";
import { a as wrapExternalContent, i as truncateSanitizedExternalContent, o as wrapWebContent } from "../external-content-IQUFD6xt.js";
import { a as parseAccessGroupAllowFromEntry } from "../allow-from-D4kg2zcb.js";
import { o as resolvePinnedMainDmOwnerFromAllowlist } from "../dm-policy-shared-C0uxEJYi.js";
import { n as buildChannelMetadata, r as buildUntrustedChannelMetadata, t as fileExists } from "../security-runtime-fAO34zGh.js";
import { n as filterSupplementalContextItems, r as shouldIncludeSupplementalContext, t as evaluateSupplementalContextVisibility } from "../context-visibility-C5CaKMWO.js";
import { t as expandAllowFromWithAccessGroups } from "../access-groups-DdAoO5yT.js";
export { FsSafeError, SsrFBlockedError, appendRegularFile, assertNoSymlinkParents, assertNoSymlinkParentsSync, buildChannelMetadata, buildUntrustedChannelMetadata, canonicalPathFromExistingAncestor, compileSafeRegexDetailed, ensurePortAvailable, evaluateSupplementalContextVisibility, expandAllowFromWithAccessGroups, extractErrorCode, fileExists, filterSupplementalContextItems, findExistingAncestor, formatErrorMessage, hasProxyEnvConfigured, isPathInside, isPrivateNetworkAllowedByPolicy, matchesHostnameAllowlist, movePathWithCopyFallback, normalizeHostname, openLocalFileSafely, parseAccessGroupAllowFromEntry, pathExists, pathExistsSync, pathScope, privateFileStoreSync, readRegularFile, readRegularFileSync, redactSensitiveText, replaceFileAtomic, resolveAbsolutePathForRead, resolveAbsolutePathForWrite, resolveExistingPathsWithinRoot, resolveLocalPathFromRootsSync, resolvePinnedHostnameWithPolicy, resolvePinnedMainDmOwnerFromAllowlist, resolvePreferredOpenClawTmpDir, resolveStrictExistingPathsWithinRoot, root, safeEqualSecret, sanitizeUntrustedFileName, shouldIncludeSupplementalContext, statRegularFile, statRegularFileSync, truncateSanitizedExternalContent, withTimeout, wrapExternalContent, wrapWebContent, writeExternalFileWithinRoot };
